name: Node CI

on: [push]

jobs:
  build:
    strategy:
      matrix:
        node-version: [12.13.1]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm run build
        run: |
          npm ci
          npm run build
  lint:
    strategy:
      matrix:
        node-version: [12.13.1]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm run lint
        run: |
          npm ci
          npm run lint
